# Generated by Django 2.2.3 on 2019-07-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('backend', models.BooleanField(default=False)),
                ('frontend', models.BooleanField(default=False)),
                ('archeng', models.BooleanField(default=False)),
                ('devops', models.BooleanField(default=False)),
                ('infrastructure', models.BooleanField(default=False)),
                ('project', models.BooleanField(default=False)),
                ('qa', models.BooleanField(default=False)),
                ('testing', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('ux', models.BooleanField(default=False)),
                ('sec_training', models.CharField(choices=[('notraining', 'No training'), ('self', 'Self taught only'), ('workplace', 'Basic workplace training or conference workshops'), ('shortcourse', 'Professional short courses (online or in person)'), ('degree', 'Diploma, degree or post-graduate')], default=None, max_length=255)),
                ('my_awareness', models.CharField(choices=[('vpoor', 'Very poor'), ('poor', 'Poor'), ('ok', 'OK'), ('good', 'Good'), ('excellent', 'Excellent'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('gender', models.CharField(choices=[('woman', 'Woman'), ('man', 'Man'), ('nbgq', 'Non-binary or gender queer'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('tech', models.CharField(max_length=255)),
                ('employer_sec_support', models.CharField(choices=[('vpoor', 'Very poor'), ('poor', 'Poor'), ('ok', 'OK'), ('good', 'Good'), ('excellent', 'Excellent'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('policy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dontknow', "I Don't know"), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('sec_workflow', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dontknow', "I Don't know"), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('review_dependencies', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('update_dependencies', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('key_rotation', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('rm_ex_dev_access', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('rm_committed_keys', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('vuln_scan', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('pentest', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('logging', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('code_review', models.CharField(choices=[('always', 'Always'), ('often', 'Often'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely'), ('never', 'Never'), ('idk', "I don't know"), ('irrelevant', 'Not relevant'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('other_barriers', models.TextField(blank=True)),
                ('no_time', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('employer_interest', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('employer_understanding', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('user_interest', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('my_interest', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('my_expertise', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('team_expertise', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('working_relationship', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('legacy', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('resources', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('difficult_docs', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('confusing_advice', models.CharField(choices=[('significant', 'Significant'), ('moderate', 'Moderate'), ('slight', 'Slight'), ('noimpact', 'None'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('comfort_approaching', models.CharField(choices=[('vuncomfy', 'Very uncomfortable'), ('suncomfy', 'Somewhat uncomfortable'), ('ambivalent', 'Ambivalent'), ('scomfy', 'Somewhat comfortable'), ('vcomfy', 'Very comfortable'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('comfort_researching', models.CharField(choices=[('vuncomfy', 'Very uncomfortable'), ('suncomfy', 'Somewhat uncomfortable'), ('ambivalent', 'Ambivalent'), ('scomfy', 'Somewhat comfortable'), ('vcomfy', 'Very comfortable'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('comfort_explanation', models.TextField(blank=True)),
                ('what_would_help', models.TextField()),
                ('story', models.TextField(blank=True)),
                ('anything_else', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
