# Generated by Django 2.2.3 on 2019-07-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('woman', 'Woman'), ('man', 'Man'), ('nbgq', 'Non-binary or gender queer'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('age_range', models.CharField(choices=[('teens', '10 - 19'), ('twenties', '20 - 29'), ('thirties', '30 - 39'), ('forties', '40 - 49'), ('fifties', '50 - 59'), ('sixties', '60 - 69'), ('seventies', '70 - 79'), ('eighties', '80 - 89'), ('nintyplus', '90+'), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('net_usage', models.CharField(choices=[('allthetime', 'Nearly all the time'), ('lots', 'Several times a day'), ('daily', 'Daily'), ('biweekly', 'Several times a week'), ('weekly', 'Once a week'), ('less', 'Less often')], default=None, max_length=255)),
                ('sec_training', models.CharField(choices=[('notraining', 'No training'), ('workplace', 'Basic workplace or community training (eg induction, library session)'), ('informal', 'Informal professional training (eg conference workshop)'), ('itworkplace', 'I work in IT but have no security training'), ('shortcourse', 'Formal short course (eg online course)'), ('degree', 'Degree level or higher')], default=None, max_length=255)),
                ('pwd_mgr', models.CharField(choices=[('everywhere', 'Yes, everywhere'), ('everywhere', 'Yes, but only for important things'), ('atwork', 'Yes, at work'), ('at_work_and_important', 'Yes, at work and for important things'), ('no', 'No'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('pwd_reuse', models.CharField(choices=[('everywhere', 'Yes, everywhere'), ('everywhere', 'Yes, but only for important things'), ('atwork', 'Yes, at work'), ('at_work_and_important', 'Yes, at work and for important things'), ('no', 'No'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('pwd_long', models.CharField(choices=[('everywhere', 'Yes, everywhere'), ('everywhere', 'Yes, but only for important things'), ('atwork', 'Yes, at work'), ('at_work_and_important', 'Yes, at work and for important things'), ('no', 'No'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('twofa', models.CharField(choices=[('everywhere', 'Yes, everywhere'), ('everywhere', 'Yes, but only for important things'), ('atwork', 'Yes, at work'), ('at_work_and_important', 'Yes, at work and for important things'), ('no', 'No'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('backups', models.CharField(choices=[('everywhere', 'Yes, everywhere'), ('everywhere', 'Yes, but only for important things'), ('atwork', 'Yes, at work'), ('at_work_and_important', 'Yes, at work and for important things'), ('no', 'No'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('vpn', models.CharField(choices=[('everywhere', 'Yes, everywhere'), ('everywhere', 'Yes, but only for important things'), ('atwork', 'Yes, at work'), ('at_work_and_important', 'Yes, at work and for important things'), ('no', 'No'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('ad_block', models.CharField(choices=[('everywhere', 'Yes, everywhere'), ('everywhere', 'Yes, but only for important things'), ('atwork', 'Yes, at work'), ('at_work_and_important', 'Yes, at work and for important things'), ('no', 'No'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('updates', models.CharField(choices=[('everywhere', 'Yes, everywhere'), ('everywhere', 'Yes, but only for important things'), ('atwork', 'Yes, at work'), ('at_work_and_important', 'Yes, at work and for important things'), ('no', 'No'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('important_things', models.TextField(blank=True)),
                ('target', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dontknow', "I Don't know"), ('noanswer', 'Prefer not to answer')], default=None, max_length=255)),
                ('target_reasons', models.TextField(blank=True)),
                ('financial', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('email_account', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('home_address', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('medical_info', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('photos', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('location_history', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('childrens_info', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('browser_search_history', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('social_sec_tfn', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('social_media', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('what_threat_looks_like', models.TextField(blank=True)),
                ('loss_of_data', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('loss_of_funds', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('dignity', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('physical_safety', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('restriction', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('emotional_safety', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('integrity', models.CharField(choices=[('most', 'Very concerned'), ('somewhat', 'Somewhat concerned'), ('ambivalent', 'Ambivalent'), ('somewhatdont', 'Somewhat unconcerned'), ('least', 'Not concerned'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('good_security_steps', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('feel_secure', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('not_concerned', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('not_a_target', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('inconvenient', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('locking_out', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('forget', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('online', models.BooleanField(default=False)),
                ('family', models.BooleanField(default=False)),
                ('guru_family', models.BooleanField(default=False)),
                ('sec_org', models.BooleanField(default=False)),
                ('gov', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('noanswer', models.BooleanField(default=False)),
                ('other_sources', models.TextField(blank=True, max_length=255)),
                ('confident', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('confused', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('scam_concern', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('trust_issues', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('time_issues', models.CharField(choices=[('ystrong', 'Strongly agree'), ('ysomewhat', 'Somewhat agree'), ('neither', 'Neither agree or disagree'), ('nsomewhat', 'Somewhat disagree'), ('nstrong', 'Strongly disagree'), ('noanswer', 'Prefer not to say')], default=None, max_length=255)),
                ('anything_else', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
