from django import forms

from .models import DevSurvey


class DevSurveyForm(forms.ModelForm):

    class Meta:
        model = DevSurvey
        fields = (
            'backend',
            'frontend',
            'archeng',
            'devops',
            'infrastructure',
            'project',
            'qa',
            'testing',
            'security',
            'ux',
            'sec_training',
            'my_awareness',
            'gender',
            'tech',
            'employer_sec_support',
            'policy',
            'sec_workflow',
            'review_dependencies',
            'update_dependencies',
            'key_rotation',
            'rm_ex_dev_access',
            'rm_committed_keys',
            'vuln_scan',
            'pentest',
            'logging',
            'code_review',
            'other_barriers',
            'no_time',
            'employer_interest',
            'employer_understanding',
            'user_interest',
            'my_interest',
            'my_expertise',
            'team_expertise',
            'working_relationship',
            'legacy',
            'resources',
            'difficult_docs',
            'confusing_advice',
            'comfort_approaching',
            'comfort_researching',
            'comfort_explanation',
            'what_would_help',
            'story',
            'anything_else',
        )
        widgets = {
            'sec_training': forms.RadioSelect,
            'my_awareness': forms.RadioSelect,
            'gender': forms.RadioSelect,
            'employer_sec_support': forms.RadioSelect,
            'policy': forms.RadioSelect,
            'sec_workflow': forms.RadioSelect,
            'review_dependencies': forms.RadioSelect,
            'update_dependencies': forms.RadioSelect,
            'key_rotation': forms.RadioSelect,
            'rm_ex_dev_access': forms.RadioSelect,
            'rm_committed_keys': forms.RadioSelect,
            'vuln_scan': forms.RadioSelect,
            'pentest': forms.RadioSelect,
            'logging': forms.RadioSelect,
            'code_review': forms.RadioSelect,
            'no_time': forms.RadioSelect,
            'employer_interest': forms.RadioSelect,
            'employer_understanding': forms.RadioSelect,
            'user_interest': forms.RadioSelect,
            'my_interest': forms.RadioSelect,
            'my_expertise': forms.RadioSelect,
            'team_expertise': forms.RadioSelect,
            'working_relationship': forms.RadioSelect,
            'legacy': forms.RadioSelect,
            'resources': forms.RadioSelect,
            'difficult_docs': forms.RadioSelect,
            'confusing_advice': forms.RadioSelect,
            'comfort_approaching': forms.RadioSelect,
            'comfort_researching': forms.RadioSelect,
        }
